// Generated by theme_tokens.py from theme.json (Ledger). Do not edit by hand.
module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "ground": "var(--c-ground)",
        "surface": "var(--c-surface)",
        "surface-2": "var(--c-surface-2)",
        "border": "var(--c-border)",
        "text": "var(--c-text)",
        "text-2": "var(--c-text-2)",
        "text-3": "var(--c-text-3)",
        "action": "var(--c-action)",
        "on-action": "var(--c-on-action)",
        "accent": "var(--c-accent)",
        "on-accent": "var(--c-on-accent)",
        "good": "var(--c-good)",
        "warn": "var(--c-warn)",
        "error": "var(--c-error)",
        "focus": "var(--c-focus)"
      },
      "fontFamily": {
        "display": [
          "Fraunces",
          "Georgia",
          "serif"
        ],
        "sans": [
          "Inter Tight",
          "system-ui",
          "sans-serif"
        ]
      },
      "borderRadius": {
        "sm": "4px",
        "md": "10px",
        "lg": "16px",
        "full": "999px"
      },
      "boxShadow": {
        "0": "none",
        "1": "0 1px 2px rgba(17, 17, 19, 0.06), 0 1px 1px rgba(17, 17, 19, 0.04)",
        "2": "0 4px 12px rgba(17, 17, 19, 0.08), 0 1px 2px rgba(17, 17, 19, 0.06)",
        "3": "0 12px 32px rgba(17, 17, 19, 0.12), 0 2px 6px rgba(17, 17, 19, 0.08)"
      },
      "fontSize": {
        "display": [
          "40px",
          {
            "lineHeight": "44px",
            "letterSpacing": "-0.02em",
            "fontWeight": "700"
          }
        ],
        "h1": [
          "32px",
          {
            "lineHeight": "38px",
            "letterSpacing": "-0.015em",
            "fontWeight": "700"
          }
        ],
        "h2": [
          "24px",
          {
            "lineHeight": "30px",
            "letterSpacing": "-0.01em",
            "fontWeight": "600"
          }
        ],
        "h3": [
          "18px",
          {
            "lineHeight": "24px",
            "letterSpacing": "-0.005em",
            "fontWeight": "600"
          }
        ],
        "lede": [
          "18px",
          {
            "lineHeight": "28px",
            "letterSpacing": "0em",
            "fontWeight": "400"
          }
        ],
        "body": [
          "16px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0em",
            "fontWeight": "400"
          }
        ],
        "small": [
          "14px",
          {
            "lineHeight": "20px",
            "letterSpacing": "0.005em",
            "fontWeight": "400"
          }
        ],
        "caption": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0.01em",
            "fontWeight": "500"
          }
        ],
        "eyebrow": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0.08em",
            "fontWeight": "600"
          }
        ]
      },
      "transitionDuration": {
        "fast": "120ms",
        "base": "200ms",
        "slow": "320ms"
      },
      "transitionTimingFunction": {
        "out": "cubic-bezier(0.2, 0.8, 0.2, 1)",
        "in-out": "cubic-bezier(0.6, 0, 0.2, 1)"
      }
    }
  }
};
