// Generated by theme_tokens.py from theme.json (Ledger). Do not edit by hand.
export const theme = {
  "light": {
    "ground": "#fcfcfd",
    "surface": "#ffffff",
    "surface-2": "#f0f0f3",
    "border": "#d9d9e0",
    "text": "#1c2024",
    "text-2": "#60646c",
    "text-3": "#8b8d98",
    "action": "#3e63dd",
    "on-action": "#ffffff",
    "accent": "#ffc53d",
    "on-accent": "#4f3422",
    "good": "#218358",
    "warn": "#ab6400",
    "error": "#ce2c31",
    "focus": "#8da4ef"
  },
  "dark": {
    "ground": "#111113",
    "surface": "#18191b",
    "surface-2": "#212225",
    "border": "#363a3f",
    "text": "#edeef0",
    "text-2": "#b0b4ba",
    "text-3": "#696e77",
    "action": "#3e63dd",
    "on-action": "#ffffff",
    "accent": "#ffc53d",
    "on-accent": "#4f3422",
    "good": "#3dd68c",
    "warn": "#ffca16",
    "error": "#ff9592",
    "focus": "#5472e4"
  },
  "space": [
    4,
    8,
    12,
    16,
    24,
    32,
    48,
    64
  ],
  "keylines": [
    24,
    72
  ],
  "radius": {
    "sm": 4,
    "md": 10,
    "lg": 16,
    "full": 999
  },
  "type": {
    "display": {
      "fontFamily": "Fraunces_700Bold",
      "fontSize": 40,
      "lineHeight": 44,
      "letterSpacing": -0.8
    },
    "h1": {
      "fontFamily": "Fraunces_700Bold",
      "fontSize": 32,
      "lineHeight": 38,
      "letterSpacing": -0.48
    },
    "h2": {
      "fontFamily": "Fraunces_600SemiBold",
      "fontSize": 24,
      "lineHeight": 30,
      "letterSpacing": -0.24
    },
    "h3": {
      "fontFamily": "InterTight_600SemiBold",
      "fontSize": 18,
      "lineHeight": 24,
      "letterSpacing": -0.09
    },
    "lede": {
      "fontFamily": "InterTight_400Regular",
      "fontSize": 18,
      "lineHeight": 28,
      "letterSpacing": 0
    },
    "body": {
      "fontFamily": "InterTight_400Regular",
      "fontSize": 16,
      "lineHeight": 24,
      "letterSpacing": 0
    },
    "small": {
      "fontFamily": "InterTight_400Regular",
      "fontSize": 14,
      "lineHeight": 20,
      "letterSpacing": 0.07
    },
    "caption": {
      "fontFamily": "InterTight_500Medium",
      "fontSize": 12,
      "lineHeight": 16,
      "letterSpacing": 0.12
    },
    "eyebrow": {
      "fontFamily": "InterTight_600SemiBold",
      "fontSize": 12,
      "lineHeight": 16,
      "letterSpacing": 0.96,
      "textTransform": "uppercase"
    }
  },
  "elevation": {
    "1": {
      "shadowColor": "#000000",
      "shadowOpacity": 0.04,
      "shadowRadius": 0.5,
      "shadowOffset": {
        "width": 0.0,
        "height": 1.0
      },
      "elevation": 1
    },
    "2": {
      "shadowColor": "#000000",
      "shadowOpacity": 0.06,
      "shadowRadius": 1.0,
      "shadowOffset": {
        "width": 0.0,
        "height": 1.0
      },
      "elevation": 1
    },
    "3": {
      "shadowColor": "#000000",
      "shadowOpacity": 0.08,
      "shadowRadius": 3.0,
      "shadowOffset": {
        "width": 0.0,
        "height": 2.0
      },
      "elevation": 3
    }
  },
  "motion": {
    "fast": 120,
    "base": 200,
    "slow": 320,
    "spring": {
      "damping": 20,
      "stiffness": 240
    }
  },
  "states": {
    "hover": 0.06,
    "pressed": 0.1,
    "disabled": 0.4,
    "focus": {
      "width": 2,
      "offset": 2
    }
  },
  "iconStroke": 1.5
} as const;

export const fonts = ["Fraunces_600SemiBold", "Fraunces_700Bold", "InterTight_400Regular", "InterTight_500Medium", "InterTight_600SemiBold"] as const;

export type Theme = typeof theme;
