#!/usr/bin/env python3
"""Turn a glow-up theme.json into every output a mockup or an app needs.

  theme_tokens.py <theme.json> --css|--css-vars|--tailwind|--tailwind3|--shadcn|--shadcn-hsl|--rn [--out file]

--css        a direction's tokens.css for mockups (fonts, variables, type and template classes)
--css-vars   only the :root and dark variable blocks, for an app's global stylesheet
--tailwind   a Tailwind v4 @theme inline block that maps utilities to the variables
--tailwind3  a Tailwind v3 config fragment to merge into theme.extend
--shadcn     shadcn/ui :root and .dark variables as OKLCH (--shadcn-hsl for HSL triplets)
--rn         a TypeScript theme module for React Native (hex colours, @expo-google-fonts names)
Prints FAIL lines and exits 1 when the theme is invalid.
"""
import json, os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from theme_core import (RAMP, ROLES, WEIGHT_NAMES, load_theme, parse, resolve, to_hex,
                        to_hsl_triplet, to_oklch_str, validate_theme)

GENERIC = "system-ui, sans-serif"
COMPAT = (("background-root", "ground"), ("text-secondary", "text-2"), ("text-tertiary", "text-3"),
          ("primary", "action"), ("button-text", "on-action"))
SHADCN_MAP = (("background", "ground"), ("foreground", "text"), ("card", "surface"), ("card-foreground", "text"),
              ("popover", "surface"), ("popover-foreground", "text"), ("primary", "action"),
              ("primary-foreground", "on-action"), ("secondary", "surface-2"), ("secondary-foreground", "text"),
              ("muted", "surface-2"), ("muted-foreground", "text-2"), ("accent", "surface-2"),
              ("accent-foreground", "text"), ("destructive", "error"), ("border", "border"), ("input", "border"),
              ("ring", "focus"))
SHADOW = re.compile(r"(-?[\d.]+)(?:px)?\s+(-?[\d.]+)(?:px)?\s+([\d.]+)(?:px)?(?:\s+(-?[\d.]+)(?:px)?)?\s+(rgba?\([^)]*\)|#[0-9a-fA-F]{3,8})")


def _head(t):
    return f"Generated by theme_tokens.py from theme.json ({t['name']}). Do not edit by hand."


def _px(v):
    return f"{float(v):g}px"


def _family(t, face):
    f = t["type"][face]
    return f'"{f["family"]}", {f.get("fallback", GENERIC)}'


def _faces(t):
    merged = {}
    for face in ("display", "body", "mono"):
        f = t["type"].get(face)
        if f and f.get("family"):
            merged.setdefault(f["family"], set()).update(f["weights"])
    return [(fam, sorted(ws)) for fam, ws in merged.items()]


def google_fonts_url(t):
    fams = "&".join(f"family={fam.replace(' ', '+')}:wght@{';'.join(str(w) for w in ws)}" for fam, ws in _faces(t))
    return f"https://fonts.googleapis.com/css2?{fams}&display=swap"


def _finite_radii(t):
    return sorted(v for v in t["shape"]["radius"].values() if v < 999)


def _root_lines(t):
    sp = t["layout"]["space"]
    rad = t["shape"]["radius"]
    finite = _finite_radii(t)
    lv = t["elevation"]["levels"]
    tpl0 = t["layout"]["templates"][0]
    m, s = t["motion"], t["states"]
    out = [f'  --f-display: {_family(t, "display")};', f'  --f-body: {_family(t, "body")};', "  --font-sans: var(--f-body);"]
    if (t["type"].get("mono") or {}).get("family"):
        out.append(f'  --f-mono: {_family(t, "mono")};')
    out += [f"  --c-{r}: {resolve(t, 'light', r)};" for r in ROLES]
    out += [f"  --c-{k}: var(--c-{v});" for k, v in COMPAT]
    out += [f"  --space-{i + 1}: {_px(v)};" for i, v in enumerate(sp)]
    out += [f"  --space-{n}: {_px(sp[min(i, len(sp) - 1)])};" for i, n in enumerate(("xs", "sm", "md", "lg", "xl", "2xl"))]
    out.append(f"  --gap-screen-x: {_px(t['layout']['keylines'][0])};")
    out += [f"  --radius-{k}: {_px(v)};" for k, v in rad.items()]
    out += [f"  --radius-card: {_px(rad.get('md', finite[0]))};",
            f"  --radius-card-raised: {_px(rad.get('lg', finite[-1]))};",
            f"  --radius-sheet: {_px(finite[-1] * 2)};"]
    out += [f"  --shadow-{k}: {v};" for k, v in lv.items()]
    out.append(f"  --shadow-card: {lv.get('1', 'none')};")
    out.append(f"  --container: {_px(tpl0['max'])};" if tpl0.get("max") else "  --container: 100%;")
    out.append(f"  --gutter: {_px(tpl0['gutter'])};")
    out += [f"  --dur-{k}: {m[k]}ms;" for k in ("fast", "base", "slow")]
    out += [f"  --ease-{k}: {v};" for k, v in m["easing"].items()]
    out += [f"  --state-hover: {s['hover']};", f"  --state-pressed: {s['pressed']};", f"  --state-disabled: {s['disabled']};",
            f"  --focus-width: {_px(s['focus']['width'])};", f"  --focus-offset: {_px(s['focus']['offset'])};",
            f"  --icon-stroke: {t['icons']['stroke']};"]
    return out


def _vars_body(t):
    dark = [f"  --c-{r}: {resolve(t, 'dark', r)};" for r in ROLES]
    return (":root {\n" + "\n".join(_root_lines(t)) + "\n}\n"
            "@media (prefers-color-scheme: dark) {\n  :root:not([data-theme=\"light\"]) {\n"
            + "\n".join("  " + line for line in dark) + "\n  }\n}\n"
            "[data-theme=\"dark\"] {\n" + "\n".join(dark) + "\n}\n")


def _decl(r):
    d = [f"font-family: var(--f-{r['face']})", f"font-size: {_px(r['size'])}", f"line-height: {_px(r['line'])}",
         f"font-weight: {r['weight']}", f"letter-spacing: {r['track']:g}em"]
    if r.get("upper"):
        d.append("text-transform: uppercase")
    return "{ " + "; ".join(d) + "; }"


def _classes(t):
    ramp = t["type"]["ramp"]
    out = [f".t-{k} {_decl(ramp[k])}" for k in RAMP]
    out.append(f".t-title {_decl(ramp['h2'])}")
    for tp in t["layout"]["templates"]:
        mx = f"max-width: {_px(tp['max'])}; " if tp.get("max") else ""
        out.append(f".tpl-{tp['id']} {{ {mx}margin-inline: auto; padding-inline: {_px(tp['margin'])}; display: grid; "
                   f"grid-template-columns: repeat({tp['columns']}, minmax(0, 1fr)); column-gap: {_px(tp['gutter'])}; "
                   f"row-gap: {_px(tp['gutter'])}; }}")
    out += [".span-all { grid-column: 1 / -1; }", ".tnum { font-variant-numeric: tabular-nums; }"]
    return "\n".join(out) + "\n"


def css(t):
    return f"/* {_head(t)} */\n@import url(\"{google_fonts_url(t)}\");\n" + _vars_body(t) + _classes(t)


def css_vars(t):
    return f"/* {_head(t)} */\n" + _vars_body(t)


def tailwind(t):
    ramp = t["type"]["ramp"]
    out = [f"  --color-{r}: var(--c-{r});" for r in ROLES]
    out += [f'  --font-display: {_family(t, "display")};', f'  --font-sans: {_family(t, "body")};']
    out += [f"  --radius-{k}: {_px(v)};" for k, v in t["shape"]["radius"].items()]
    out += [f"  --shadow-{k}: {v};" for k, v in t["elevation"]["levels"].items()]
    out.append(f"  --spacing: {_px(t['layout']['space'][0])};")
    for k in RAMP:
        r = ramp[k]
        out += [f"  --text-{k}: {_px(r['size'])};", f"  --text-{k}--line-height: {_px(r['line'])};",
                f"  --text-{k}--letter-spacing: {r['track']:g}em;", f"  --text-{k}--font-weight: {r['weight']};"]
    out += [f"  --ease-{k}: {v};" for k, v in t["motion"]["easing"].items()]
    return f"/* {_head(t)} */\n@theme inline {{\n" + "\n".join(out) + "\n}\n"


def tailwind3(t):
    ramp = t["type"]["ramp"]
    fam = lambda face: [t["type"][face]["family"]] + [x.strip() for x in t["type"][face].get("fallback", GENERIC).split(",")]
    ext = {
        "colors": {r: f"var(--c-{r})" for r in ROLES},
        "fontFamily": {"display": fam("display"), "sans": fam("body")},
        "borderRadius": {k: _px(v) for k, v in t["shape"]["radius"].items()},
        "boxShadow": dict(t["elevation"]["levels"]),
        "fontSize": {k: [_px(ramp[k]["size"]), {"lineHeight": _px(ramp[k]["line"]), "letterSpacing": f"{ramp[k]['track']:g}em",
                                                 "fontWeight": str(ramp[k]["weight"])}] for k in RAMP},
        "transitionDuration": {k: f"{t['motion'][k]}ms" for k in ("fast", "base", "slow")},
        "transitionTimingFunction": dict(t["motion"]["easing"]),
    }
    return f"// {_head(t)}\nmodule.exports = " + json.dumps({"theme": {"extend": ext}}, indent=2, ensure_ascii=False) + ";\n"


def shadcn(t, hsl=False):
    fmt = (lambda c: to_hsl_triplet(parse(c))) if hsl else (lambda c: to_oklch_str(parse(c)))
    block = lambda mode: "\n".join(f"  --{k}: {fmt(resolve(t, mode, r))};" for k, r in SHADCN_MAP)
    md = t["shape"]["radius"].get("md", _finite_radii(t)[0])
    return (f"/* {_head(t)} */\n:root {{\n" + block("light") + f"\n  --radius: {md / 16:g}rem;\n}}\n"
            ".dark {\n" + block("dark") + "\n}\n")


def _rn_shadow(v):
    last = None
    for last in SHADOW.finditer(v):
        pass
    if not last:
        return None
    x, y, blur, _, col = last.groups()
    alpha = float(col.rstrip(")").split(",")[-1]) if col.startswith("rgba") else 1.0
    return {"shadowColor": "#000000", "shadowOpacity": alpha, "shadowRadius": float(blur) / 2,
            "shadowOffset": {"width": float(x), "height": float(y)}, "elevation": max(1, round(float(blur) / 2))}


def rn(t):
    ramp = t["type"]["ramp"]
    font = lambda face, w: t["type"][face]["family"].replace(" ", "") + f"_{w}{WEIGHT_NAMES[w]}"
    typ = {}
    for k in RAMP:
        r = ramp[k]
        typ[k] = {"fontFamily": font(r["face"], r["weight"]), "fontSize": r["size"], "lineHeight": r["line"],
                  "letterSpacing": round(r["track"] * r["size"], 2)}
        if r.get("upper"):
            typ[k]["textTransform"] = "uppercase"
    motion = {k: t["motion"][k] for k in ("fast", "base", "slow")}
    if t["motion"].get("spring"):
        motion["spring"] = t["motion"]["spring"]
    obj = {
        "light": {r: to_hex(parse(resolve(t, "light", r))) for r in ROLES},
        "dark": {r: to_hex(parse(resolve(t, "dark", r))) for r in ROLES},
        "space": t["layout"]["space"],
        "keylines": t["layout"]["keylines"],
        "radius": t["shape"]["radius"],
        "type": typ,
        "elevation": {k: s for k, s in ((k, _rn_shadow(v)) for k, v in t["elevation"]["levels"].items()) if s},
        "motion": motion,
        "states": t["states"],
        "iconStroke": t["icons"]["stroke"],
    }
    fonts = sorted({font(face, w) for face in ("display", "body", "mono") if (t["type"].get(face) or {}).get("family")
                    for w in t["type"][face]["weights"]})
    return (f"// {_head(t)}\nexport const theme = " + json.dumps(obj, indent=2, ensure_ascii=False) + " as const;\n\n"
            "export const fonts = " + json.dumps(fonts) + " as const;\n\nexport type Theme = typeof theme;\n")


MODES = {"--css": css, "--css-vars": css_vars, "--tailwind": tailwind, "--tailwind3": tailwind3,
         "--shadcn": shadcn, "--shadcn-hsl": lambda t: shadcn(t, hsl=True), "--rn": rn}


def main(argv):
    if len(argv) < 2 or argv[1] not in MODES:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    t = load_theme(argv[0])
    errs = validate_theme(t)
    if errs:
        for e in errs:
            print("FAIL", e)
        return 1
    out = MODES[argv[1]](t)
    if "--out" in argv:
        with open(argv[argv.index("--out") + 1], "w", encoding="utf-8") as f:
            f.write(out)
    else:
        sys.stdout.write(out)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
